# docker build -t portal:latest .
# docker run -d -p 5001:5001 portal

# build stage
FROM node:lts-alpine as build-stage
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
RUN git clone https://github.com/namith-scindhia-newpage-io/adf-portal.git
WORKDIR /usr/src/app/adf-portal/portal
RUN npm install
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /usr/src/app/adf-portal/portal/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]